Update LetsEncrypt certs
naps-dev/dco-core pull request #31
Opened 2023-05-24 22:10 UTC by laurenmengert

## Type of change

Please delete options that are not relevant.

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

This PR renews the LetsEncrypt certificate

For example:

Currently, the software does X, but this PR will allow it to do Y.

Currently, the software does not do X, but this PR will allow it to do X.

Currently, the software does X when specific thing happens causing bad things to happens, but this PR will fix it to do Y without the bad things.

New dependencies added:
- dependency 1 for reason
- dependency 2 for reason

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration - Change as necessary**:
* Kubernetes version:
* Hardware:
* Capability:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added a plain language explanation of the changes to the Unreleased section of the CHANGELOG.md file

2023-05-31 18:31 UTC, bburky requested changes
The certificate only has a `vp.bigbang.dev` SAN, it is missing the wildcard `*.vp.bigbang.dev` SAN.

You can check with `openssl x509 -noout -text -in cert.pem` which contains the following output
```
            X509v3 Subject Alternative Name: 
                DNS:vp.bigbang.dev
```

We need to reissue the cert with the wildcard SAN.

2023-06-01 20:15 UTC, mikevanhemert approved these changes
Nicely done!

2023-06-02 16:58 UTC, docandrew approved these changes

2023-06-02 16:58 UTC, docandrew approved these changes

2023-06-02 16:59 UTC, docandrew approved these changes

2023-06-02 17:21 UTC, merged